### ISSUE TITLE
Please commit source code.

### ISSUE THREAD

**Issue by jbeuckm** [diffractometer/hujo.bio#2]

**Comment by diffractometer** [comment]
Is there an alternative to .als Ableton files that can be read by Ableton? It's relatively easy to source control, now that github saves big files this could get interesting...

**Comment by jbeuckm** [comment]
![Alt text](http://www.cvgm.net/static/media/platform/image/generalmidi_platform.png)

**Comment by diffractometer** [comment]
☆ LOL ☆

**Comment by diffractometer** [comment]
killing me softly

**Comment by jbeuckm** [comment]
How do we talk about binary sonical data in the VCS context?

**Comment by diffractometer** [comment]
Did you see ~> https://github.com/blog/1986-announcing-git-large-file-storage-lfs, we could add a project easily...

Or we could go l33t and do pure midi with a standard library?

**Comment by jbeuckm** [comment]
oh neat! there's also midi sample dump standard.

**Comment by jbeuckm** [comment]
so you release your album with LFS and people clone it to work on it and submit pull requests.

**Comment by diffractometer** [comment]
Exactly!

**Comment by jbeuckm** [comment]
We need a diff program to a/b in the browser or in the github app. Visual waveform + spectrogram + playback of change and project with change.

**Comment by diffractometer** [comment]
True, would be hard with Ableton as it renders. Could use something like Saucelabs (for tests) which automatically renders the .als file when you push?

**Comment by diffractometer** [comment]
...badges.... we could have badges!

**Comment by jbeuckm** [comment]
Ablt has a headless renderer? Might need to be a big open source standards based project to do this stuff. BTC micropayments to render in the cloud.

**Comment by diffractometer** [comment]
!!! Woah yeah totally... headless Ablt bonkers to think about. No way they'd let us do that? This could be the time to jump to Overtone? Have you messed with it yet? I'm not sure how difficult it it to get a midi ctrl / sampler working...

**Comment by jbeuckm** [comment]
CSound is amenable aside from the problem of binaries.

**Comment by jbeuckm** [comment]
Gotta get that multitrack DAW going. MIDI sample dump and sysex could be standardized enough to handle a lot.

**Comment by diffractometer** [comment]
Hmmmmm.... tru!

**Comment by diffractometer** [comment]
https://www.youtube.com/watch?v=Lp_kQh34EWA stuff is exciting to me... but not a DAW per se?

**Comment by jbeuckm** [comment]
Looks like you can build csound on Travis: https://travis-ci.org/csound/csound/builds/60265084

So... 
1. clone csound
2. build on travis
3. cache as dependency on travis
4. delete csound files in repo
5. write brilliant csound code to auto-render on travis
6. write uploader that posts your audio somewhere from travis (LFS?)

**Comment by diffractometer** [comment]
gtfo wow!

**Comment by jbeuckm** [comment]
you eff with ardour?

**Comment by jbeuckm** [comment]
![ardour_headless](https://cloud.githubusercontent.com/assets/137068/7400125/31d3cf1c-ee80-11e4-9e5f-a3ef59003b78.png)

**Comment by diffractometer** [comment]
gtfo never heard of it... you gotta stop my brain is going to eplode :8ball:
